-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1021210
-- Name: Cyber Knights: Flashpoint
addappid(1021210) -- Cyber Knights: Flashpoint
addappid(1021212,0,"ca8eecda387085ee0ddead4b8e6f11eb31acbf246bff8341d302488f02613fc4") -- Depot 1 (1021212_1718519487247844289.manifest)
setManifestid(1021212,"1718519487247844289")