-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1030300
-- Name: Hollow Knight: Silksong
addappid(1030300) -- Hollow Knight: Silksong
addappid(1030303,0,"ea761f41bd28ae29fd22375e81702eadc64796099fd9dcf01ea2a190536cc7c3") -- Depot 1 (1030303_1617544312110692774.manifest)
setManifestid(1030303,"1617544312110692774")
addappid(1030301,0,"f4a253f96969f93b8a9392cddf6f1b779886ea10a160e7ca148b92bae09abd28") -- Depot 2 (1030301_5977483240701257214.manifest)
setManifestid(1030301,"5977483240701257214")
addappid(1030302,0,"bc736fb6e74601f627b4890559822b4b8e786e36e949b881dcd25419e8a15e9e") -- Depot 3 (1030302_7917356342743942630.manifest)
setManifestid(1030302,"7917356342743942630")