-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1040200
-- Name: Crime Scene Cleaner
addappid(1040200) -- Crime Scene Cleaner
addappid(1040201,0,"c674332af23f9b6fcc58092e93db43d62fe38a9b004985697e490bde97b45548") -- Depot 1 (1040201_6728454781263644247.manifest)
setManifestid(1040201,"6728454781263644247")