-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1044620
-- Name: Aokana - Four Rhythms Across the Blue
addappid(1044620) -- Aokana - Four Rhythms Across the Blue
addappid(1966540,0,"9d67124c756a85a8c6115c471b6694bec604df1ccfa9ea8ecc44744daacfc25d") -- Depot 1 (1966540_5093831643860917657.manifest)
setManifestid(1966540,"5093831643860917657")
addappid(2022801,0,"d6ce053fcf077b0d563bfbfb0097cf11a0381bb280d0a5af8bdb16ebb27ed9d1") -- Depot 2 (2022801_3395569265615405461.manifest)
setManifestid(2022801,"3395569265615405461")
addappid(1966541,0,"2c2d64c11ec16a8d7f980ced69d635c558e1fc79f0b9f66df3f7a41fc79a182f") -- Depot 3 (1966541_6849251102774804024.manifest)
setManifestid(1966541,"6849251102774804024")
addappid(2022802,0,"83d392ef0b19831bdf81e01e5503a71eb897d2be8d3b698a89dc43cc39fd0506") -- Depot 4 (2022802_288261122734015286.manifest)
setManifestid(2022802,"288261122734015286")
addappid(1219150,0,"205e9eaa30e63e10a340ad5057e4dba01087016109bb4065215bfb62b473a6dc") -- Depot 5 (1219150_1624156722750849597.manifest)
setManifestid(1219150,"1624156722750849597")
addappid(1162110,0,"75cada30e8bfa481e7d923acc24e1593c5e1cf3f4df79ec9b81690af8f97a670") -- Depot 6 (1162110_5804530054537620033.manifest)
setManifestid(1162110,"5804530054537620033")
addappid(1044621,0,"e4de2e5ad93821687c7cc71aec870246915e61b66bec007091abb381da5454a1") -- Depot 7 (1044621_1124321592740122839.manifest)
setManifestid(1044621,"1124321592740122839")
addappid(1219130,0,"7b39c1cbdc7abf346f2879d68ddf26e62080a42daf5ca6da87d0889ef27093c8") -- Depot 8 (1219130_3496350920010610244.manifest)
setManifestid(1219130,"3496350920010610244")