-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 108600
-- Name: Project Zomboid
addappid(108600) -- Project Zomboid
addappid(228986,0,"51dd3611d28621644730736f3bb1fd6b960053a45cd79123f2b9a80c9181dad5") -- Depot 1 (228986_8782296191957114623.manifest)
setManifestid(228986,"8782296191957114623")
addappid(108604,0,"3f8e8c70818c5469711aeaefe50b4f280028b72dfd7f7a4c83b6bd747e4a382a") -- Depot 2 (108604_8495676860137747126.manifest)
setManifestid(108604,"8495676860137747126")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 3 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(228987,0,"cf0622b6dec67606fdc42e7afa5ede78cb33e38dfab82670c5ec7e1404e4984e") -- Depot 4 (228987_4302102680580581867.manifest)
setManifestid(228987,"4302102680580581867")
addappid(228983,0,"77c8e812cd79e67e2d376721253ebb07e06b3646f05671c6c9517b27be14734b") -- Depot 5 (228983_8124929965194586177.manifest)
setManifestid(228983,"8124929965194586177")
addappid(108603,0,"0b2a31059fa239993389b69ca9a0bebd9e3cbc8ccb446335c2becbe85060b0c4") -- Depot 6 (108603_6529967175871940863.manifest)
setManifestid(108603,"6529967175871940863")
addappid(108602,0,"2c6834d3d5c0e48329883a18abe5614aa868c3e7911fc582c613cec21b3a5d1c") -- Depot 7 (108602_362539403589738701.manifest)
setManifestid(108602,"362539403589738701")
addappid(228985,0,"21a2f639584d9bd462c5c4b3e10f881cba8a17ae674c830c4f083551cd356e9c") -- Depot 8 (228985_3966345552745568756.manifest)
setManifestid(228985,"3966345552745568756")