-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1145360
-- Name: Hades
addappid(1145360) -- Hades
addappid(1145363,0,"b88219eb2aee190d115e532ef9feea08c69bbc53bb1f959a2c48f3739f871b31") -- Depot 1 (1145363_2572656066874346283.manifest)
setManifestid(1145363,"2572656066874346283")
addappid(1206340,0,"c9345233ddbba0dd102b637212b8a892325701e165ffdd994cf90c6794551d6a") -- Depot 2 (1206340_1347596415684508815.manifest)
setManifestid(1206340,"1347596415684508815")
addappid(1145361,0,"e7db1a4f43363b9d751ed9e888334353425704ea0db26c8434015e516a482f4d") -- Depot 3 (1145361_5173085471687919135.manifest)
setManifestid(1145361,"5173085471687919135")
addappid(1145364,0,"c70c6707a01507e124d35ac0e1644ee6210f383a1ae759aa252478cbd1ca7e0e") -- Depot 4 (1145364_6896671991921324741.manifest)
setManifestid(1145364,"6896671991921324741")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 5 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(229006,0,"9bc3e05ce55153e5c315cb18024602ca15958a7be03adc5ffbe53b00a8524416") -- Depot 6 (229006_1784011429307107530.manifest)
setManifestid(229006,"1784011429307107530")
addappid(1206341,0,"d0cbd567d11fca873af7c65482965f6ef164ad4b58b208408ba7a05e61ee49a6") -- Depot 7 (1206341_5338171915262780986.manifest)
setManifestid(1206341,"5338171915262780986")