-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1145350
-- Name: Hades II
addappid(1145350) -- Hades II
addappid(1145352,0,"ff02298666a5470ddca19f89593983136f6d1727fc82957ca6b847133783b4e7") -- Depot 1 (1145352_6961261004728985549.manifest)
setManifestid(1145352,"6961261004728985549")
addappid(1145354,0,"71f0364cb7bd2b7d7755605c7983bf2b73101a6e2e0ef6b7082d275a4650f7e5") -- Depot 2 (1145354_3274726608137700194.manifest)
setManifestid(1145354,"3274726608137700194")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 3 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(1145355,0,"67def0278f458945e71a75914c686e5bf4d3f90c8b4320795c3b78ad999afc56") -- Depot 4 (1145355_2060204187511838131.manifest)
setManifestid(1145355,"2060204187511838131")