-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1158160
-- Name: Coral Island
addappid(1158160) -- Coral Island
addappid(2471180,0,"61aa13efb38e3f9ffaf22c018bde687a97b95b559d21406a6bbc47da860be1ab") -- Depot 1 (2471180_1643256457515370317.manifest)
setManifestid(2471180,"1643256457515370317")
addappid(1158161,0,"e9303b2124c42a0c9cfc882e92469d8ceb392056ec283045ac876c31df4f5e65") -- Depot 2 (1158161_3209921864859881212.manifest)
setManifestid(1158161,"3209921864859881212")
addappid(2537800,0,"2c18bb7df0d4f51d0d81f95eefaa22e3966f628e7f4defbc9d7d1978476a8b0b") -- Depot 3 (2537800_9022386239993204092.manifest)
setManifestid(2537800,"9022386239993204092")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 4 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 5 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(2273380,0,"f2946bf1df6964993d9597e6f2ac42e9aca3ef22d2f7c7145c3823b241966bf2") -- Depot 6 (2273380_8577500605315709614.manifest)
setManifestid(2273380,"8577500605315709614")