-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1174180
-- Name: Red Dead Redemption 2
addappid(1174180) -- Red Dead Redemption 2
addappid(1174181,0,"6fbf0f4b33fd5111d0832f0fb63a4d185c5321901ef95776c73e6e10b203bc25") -- Depot 1 (1174181_4757128409362785099.manifest)
setManifestid(1174181,"4757128409362785099")
addappid(1174184,0,"506c8f971b77f5c39f8baa54fac090e79bf32e19d92eca2a34cba9569bbe5d8a") -- Depot 2 (1174184_2698939236196220127.manifest)
setManifestid(1174184,"2698939236196220127")
addappid(1174183,0,"cd51ee7e8adde797736bc283f9d434fae0aac28753e3f38a29a78aac298c0ccf") -- Depot 3 (1174183_4785346550216140531.manifest)
setManifestid(1174183,"4785346550216140531")
addappid(1174185,0,"6fe9c5b4e41f1f91b6a775dd562515e9652570cc607caedef2bc4a9d522fea4d") -- Depot 4 (1174185_8173342615013177810.manifest)
setManifestid(1174185,"8173342615013177810")
addappid(228987,0,"cf0622b6dec67606fdc42e7afa5ede78cb33e38dfab82670c5ec7e1404e4984e") -- Depot 5 (228987_4302102680580581867.manifest)
setManifestid(228987,"4302102680580581867")
addappid(1174186,0,"0ef7331ad866994474a72131eeb1a5667dc8c9f7be87b4e1d805f288e1d49432") -- Depot 6 (1174186_357926288062992323.manifest)
setManifestid(1174186,"357926288062992323")
addappid(1899671,0,"b7921da5e50d00b2238d0fe870a354cb572bc5d397955fef02a439103f62827b") -- Depot 7 (1899671_3704256598511448914.manifest)
setManifestid(1899671,"3704256598511448914")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 8 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1174182,0,"0824e4e00b9d464a1352b0eaa60416ee3bfe0f3b416459991dc6fca87e84366f") -- Depot 9 (1174182_2258488483491377476.manifest)
setManifestid(1174182,"2258488483491377476")