-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 12210
-- Name: Grand Theft Auto IV: The Complete Edition
addappid(12210) -- Grand Theft Auto IV: The Complete Edition
addappid(12217,0,"050c5432482073005c36629ad7372baeafb6d1f63b6b8175936feb4ad8521d1c") -- Depot 1 (12217_703090685957058760.manifest)
setManifestid(12217,"703090685957058760")
addappid(12218,0,"3446117408a17195591f5a98c1f64d2ca9a49dcdeb93a90fec8ceb63cb1cf249") -- Depot 2 (12218_5435507331887440070.manifest)
setManifestid(12218,"5435507331887440070")
addappid(12216,0,"ef7603bd0f512678f2832b71bcb340b950fd5d8ed5f52e0129300538727d1787") -- Depot 3 (12216_716802607004606457.manifest)
setManifestid(12216,"716802607004606457")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 4 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(12215,0,"70a582f0d5f9cbf610ccbac1a905c7d5c8f0f3b420412ee754779141d9a89e77") -- Depot 5 (12215_5596831668192471551.manifest)
setManifestid(12215,"5596831668192471551")
addappid(12211,0,"155186d97af14c948ac35351ac345c108046167384eb2b898802f158bfd111b4") -- Depot 6 (12211_8070600747380932868.manifest)
setManifestid(12211,"8070600747380932868")
addappid(1899671,0,"b7921da5e50d00b2238d0fe870a354cb572bc5d397955fef02a439103f62827b") -- Depot 7 (1899671_3704256598511448914.manifest)
setManifestid(1899671,"3704256598511448914")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 8 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(12213,0,"e927e10529530ef0a1798c945c7fea9d3a4bd8cb2bac061587c193afbe0dfeec") -- Depot 9 (12213_7959739752369022030.manifest)
setManifestid(12213,"7959739752369022030")
addappid(12214,0,"f47f42a9df6c82ac4c134478cd1a0c95bdb32f686a3c4033ee8b9735c3999529") -- Depot 10 (12214_8513070578700495865.manifest)
setManifestid(12214,"8513070578700495865")
addappid(12212,0,"63df369c3038e5c927f585fc81b41f5b669795976ac9af4d27a2add6c57733ca") -- Depot 11 (12212_5029883714475696364.manifest)
setManifestid(12212,"5029883714475696364")