-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1249970
-- Name: Test Drive Unlimited Solar Crown
addappid(1249970) -- Test Drive Unlimited Solar Crown
addappid(1249971,0,"ef894cda9509eea638e332e510f8d089c04994ef8ffafdfd3cc721414b0b4176") -- Depot 1 (1249971_2984559789861827962.manifest)
setManifestid(1249971,"2984559789861827962")
addappid(228984,0,"df7df98d3134f5e0009d5ebcaaf3bbb91ea2f7cbad81a37a9d16bc1835f57068") -- Depot 2 (228984_2547553897526095397.manifest)
setManifestid(228984,"2547553897526095397")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")