-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1342490
-- Name: Daemon X Machina: Titanic Scion
addappid(1342490) -- Daemon X Machina: Titanic Scion
addappid(3779150,0,"7f846f37bcfb01890a3bf2c2a91724c2342f38d3085da2354f573476227b405b") -- Depot 1 (3779150_951698471833675111.manifest)
setManifestid(3779150,"951698471833675111")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 2 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 3 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1342491,0,"c6540bdf8c309fb168778b2fbe5a1f6fd5802ca36eb9ac410f78e2bce2d4b57f") -- Depot 4 (1342491_5013354445104201572.manifest)
setManifestid(1342491,"5013354445104201572")