-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1392860
-- Name: Little Nightmares III
addappid(1392860) -- Little Nightmares III
addappid(229007,0,"eba9fa9ff4f811929c119074450f49f739113bcae9317ded9bea262aa21ec58d") -- Depot 1 (229007_4477590687906973371.manifest)
setManifestid(229007,"4477590687906973371")
addappid(1392863,0,"2a40e8e4f16a349cec1ad4cdd732e6a88afb1d0676c8de3061c87c7d815343d0") -- Depot 2 (1392863_5486992888714282187.manifest)
setManifestid(1392863,"5486992888714282187")
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 3 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(229033,0,"9a789440bbc16131547ac6c062e5f168f7684da533a2899a71fdfaaeec21efc3") -- Depot 4 (229033_2059065101492814639.manifest)
setManifestid(229033,"2059065101492814639")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 5 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 6 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(229006,0,"9bc3e05ce55153e5c315cb18024602ca15958a7be03adc5ffbe53b00a8524416") -- Depot 7 (229006_1784011429307107530.manifest)
setManifestid(229006,"1784011429307107530")