-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1394470
-- Name: Umami Grove
addappid(1394470) -- Umami Grove
addappid(1394471,0,"8d3158db22f1dff7735792ead9c64b3ec2df6dc50ee9579fd4dfb513288c69c0") -- Depot 1 (1394471_2431160555561010737.manifest)
setManifestid(1394471,"2431160555561010737")