-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1490890
-- Name: Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles
addappid(1490890) -- Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles
addappid(1760470,0,"70a688482c965ca7753eff82322f589bf14c05bcc6e641908f54ab17610a84b0") -- Depot 1 (1760470_6120140167597313636.manifest)
setManifestid(1760470,"6120140167597313636")
addappid(1760500,0,"07cfb0664655d5544016861463b28175d000e7880ecaea791cc4739c26f8069f") -- Depot 2 (1760500_694275557452403358.manifest)
setManifestid(1760500,"694275557452403358")
addappid(1490891,0,"20196f9d842139359a0275126f03992d9510d5b96c4213c38ad6d95c6d72d402") -- Depot 3 (1490891_5461881877101609571.manifest)
setManifestid(1490891,"5461881877101609571")
addappid(1490893,0,"aff3930bfe0975c776a9dbe8c34b6b96167ab0db098e0764ba3b15b288ed1548") -- Depot 4 (1490893_4406597967236367118.manifest)
setManifestid(1490893,"4406597967236367118")
addappid(1760480,0,"82dca9e50950f252b389747c8f4e33a4754f34fd7d8e93b2d8a013532b6a4d0e") -- Depot 5 (1760480_43390555700542166.manifest)
setManifestid(1760480,"43390555700542166")
addappid(1490894,0,"d2ec4b7a405fdbac76fa443457c80f5b157516d888a2c8abe599a50033cf2e32") -- Depot 6 (1490894_665670508748928184.manifest)
setManifestid(1490894,"665670508748928184")
addappid(228988,0,"1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- Depot 7 (228988_6645201662696499616.manifest)
setManifestid(228988,"6645201662696499616")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 8 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")
addappid(1760490,0,"c5e244432a04f26054022a4f38c1419c2c743df9b79d9a706bdf38cf2fb41856") -- Depot 9 (1760490_3433579119073246874.manifest)
setManifestid(1760490,"3433579119073246874")
addappid(1777140,0,"010c8f072b3fc9a3f7b089be2e56dedc947bc221f9bf5ee6e98bb09bc6d0b032") -- Depot 10 (1777140_7087906368917676089.manifest)
setManifestid(1777140,"7087906368917676089")