-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1501750
-- Name: Lords of the Fallen
addappid(1501750) -- Lords of the Fallen
addappid(228989,0,"ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- Depot 1 (228989_3514306556860204959.manifest)
setManifestid(228989,"3514306556860204959")
addappid(2387921,0,"e69a9bfb62c1ca78c5fbb00518ff2251ada2f55dadfdbe8d842ee5174c83c3ac") -- Depot 2 (2387921_6553904194185226573.manifest)
setManifestid(2387921,"6553904194185226573")
addappid(1501751,0,"c86a5d17ac060ed8c27bc9840a5eb75890d5d8cf1908993635a947d13a30076b") -- Depot 3 (1501751_7583793689358649525.manifest)
setManifestid(1501751,"7583793689358649525")
addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- Depot 4 (228990_1829726630299308803.manifest)
setManifestid(228990,"1829726630299308803")